Repository artsy/kaws, pull requests merged in 2019-10, with the labels that each got.

#162 Deprecate snake case names, introduce new camel case fields
  _schema.graphql
  src/Entities/Collection.ts
  src/Entities/CollectionQuery.ts
  src/utils/__tests__/__snapshots__/createSchema.test.ts.snap
Labels: Jira Synced

#165 Update point people for repo
  README.md
Labels: Merge On Green

#163 Add internalID fields to kaws schema
  _schema.graphql
  src/Entities/Collection.ts
  src/Entities/CollectionGroup.ts
  src/Entities/CollectionQuery.ts
  src/utils/__tests__/__snapshots__/createSchema.test.ts.snap
Labels: Jira Synced

#166 fixes some issues with price guidance
  src/__tests__/collectionHubs.test.ts
  src/__tests__/price_guidance_integration.test.ts
  src/utils/__tests__/getPriceGuidance.test.ts
  src/utils/getPriceGuidance.ts
  src/utils/updateDatabase.ts
Labels: Jira Synced, woof!

#164 Deploy
  README.md
  _schema.graphql
  src/Entities/Collection.ts
  src/Entities/CollectionGroup.ts
  src/Entities/CollectionQuery.ts
  src/__tests__/collectionHubs.test.ts
  src/__tests__/price_guidance_integration.test.ts
  src/utils/__tests__/__snapshots__/createSchema.test.ts.snap
  src/utils/__tests__/getPriceGuidance.test.ts
  src/utils/getPriceGuidance.ts
  src/utils/updateDatabase.ts
Labels: Jira Synced

#168 Add featured_artist_exclusion_ids column to exclude artists from feat…
  _schema.graphql
  src/Entities/Collection.ts
  src/Routes/GSheetImport.ts
  src/Routes/__tests__/GSheetImport.test.ts
  src/utils/__tests__/__snapshots__/createSchema.test.ts.snap
  src/utils/processInput.ts
Labels: Jira Synced

#169 Deploy
  _schema.graphql
  src/Entities/Collection.ts
  src/Routes/GSheetImport.ts
  src/Routes/__tests__/GSheetImport.test.ts
  src/utils/__tests__/__snapshots__/createSchema.test.ts.snap
  src/utils/processInput.ts
  yarn.lock
Labels: Jira Synced
